apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  tags:
    - time
    - machine
  name: wayback-archive-storage
  description: wayback-machine
  links:
    - url: https://github.com/shukibakbuki/dingdong
      title: Github Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: repos
