# .github/workflows/dependency-review.yml
name: Dependency Review

on:
  pull_request:
    branches:
      - main  # or your default branch
      - 'release/*'  # optional, more branches

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high  # fail PR if vulnerability is High or above
          allow-licenses: MIT, Apache-2.0 # optional, license allowlist
